//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MMM d, yyyy.
        /// </summary>
        public static string AbbrevDate {
            get {
                return ResourceManager.GetString("AbbrevDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to To see all records, clear both fields.
        /// </summary>
        public static string AllRecords {
            get {
                return ResourceManager.GetString("AllRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booked.
        /// </summary>
        public static string Booked {
            get {
                return ResourceManager.GetString("Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bookings.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booking Date.
        /// </summary>
        public static string BookingDate {
            get {
                return ResourceManager.GetString("BookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Bookings Summary.
        /// </summary>
        public static string BookingsSummary {
            get {
                return ResourceManager.GetString("BookingsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to If you would like to view a public summary of bookings of the Drydock, the North Landing Wharf and the South Jetty facilities at the Esquimalt Graving Dock without signing in or registering an account, first select a facility and then, select a period of time..
        /// </summary>
        public static string BookingsSummaryDescription {
            get {
                return ResourceManager.GetString("BookingsSummaryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Book space.
        /// </summary>
        public static string BookSpace {
            get {
                return ResourceManager.GetString("BookSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to This field is case sensitive.
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to a company.
        /// </summary>
        public static string CompanyRequest {
            get {
                return ResourceManager.GetString("CompanyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} companies.
        /// </summary>
        public static string CompanyRequests {
            get {
                return ResourceManager.GetString("CompanyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Conduct a new search.
        /// </summary>
        public static string ConductNewSearch {
            get {
                return ResourceManager.GetString("ConductNewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Consult the public summary of bookings.
        /// </summary>
        public static string ConsultBookingsSummary {
            get {
                return ResourceManager.GetString("ConsultBookingsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Contact Esquimalt Graving Dock.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Add.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Docking Dates.
        /// </summary>
        public static string DockingDates {
            get {
                return ResourceManager.GetString("DockingDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Drydock.
        /// </summary>
        public static string Drydock {
            get {
                return ResourceManager.GetString("Drydock", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Esquimalt Graving Dock.
        /// </summary>
        public static string EGD {
            get {
                return ResourceManager.GetString("EGD", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Email address (yourname@domain.com).
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Fees.
        /// </summary>
        public static string Fees {
            get {
                return ResourceManager.GetString("Fees", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The Esquimalt Graving Dock booking fee is $4,800.00 Canadian plus $240.00 GST for a total of $5,040.00 payable in cash, certified cheque drawn on a Canadian bank or by an international money order. Effective April 1, 2008, interest will be applied on any account outstanding over 30 days. Reservation requests are tentative until the booking fee is paid. Booking fees are non-refundable..
        /// </summary>
        public static string FeesDescription {
            get {
                return ResourceManager.GetString("FeesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Forgot your password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to From Date:.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Important notices about the Esquimalt Graving Dock.
        /// </summary>
        public static string ImportantNotices {
            get {
                return ResourceManager.GetString("ImportantNotices", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Companies and individuals can book space for vessels at our facilities on a first-come, first-served basis. You can also consult the public summary of bookings. The Esquimalt Graving Dock is the largest solid-bottom commercial drydock on the West Coast of Americas, which is located in an ice-free harbour on Vancouver Island..
        /// </summary>
        public static string IndexDescription {
            get {
                return ResourceManager.GetString("IndexDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Booking Space at the Esquimalt Graving Dock.
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign in to book or cancel a space.
        /// </summary>
        public static string JumpToSignIn {
            get {
                return ResourceManager.GetString("JumpToSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Learn more about the Esquimalt Graving Dock.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to MMMM d, yyyy.
        /// </summary>
        public static string LongDate {
            get {
                return ResourceManager.GetString("LongDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Manage your Esquimalt Graving Dock account.
        /// </summary>
        public static string ManageYourAccount {
            get {
                return ResourceManager.GetString("ManageYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Government of Canada, Public Works and Government Services, Real Property Branch.
        /// </summary>
        public static string MetaCreator {
            get {
                return ResourceManager.GetString("MetaCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Companies and individuals can book space for a watercraft at any of the facilities of the Esquimalt Graving Dock on a first-come, first-served basis or can consult the public summary of bookings..
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Esquimalt Graving Dock, EGD, Drydock, North Landing Wharf, South Jetty,  bookings, space booking, reserve a space, reservation, cancellation, booking dates, docking dates, commercial drydock, dry-dock, ship repair facility.
        /// </summary>
        public static string MetaKeywords {
            get {
                return ResourceManager.GetString("MetaKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Government of Canada; marine installations; wharfs; vessels; ships;.
        /// </summary>
        public static string MetaSubject {
            get {
                return ResourceManager.GetString("MetaSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vessels design, construction and maintenance – Marine transportation – Transport and infrastructure.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to For more information.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You have {0} that need to be approved..
        /// </summary>
        public static string NeedingApproval {
            get {
                return ResourceManager.GetString("NeedingApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are no bookings to view..
        /// </summary>
        public static string NoBookings {
            get {
                return ResourceManager.GetString("NoBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to North Landing Wharf.
        /// </summary>
        public static string NorthJetty {
            get {
                return ResourceManager.GetString("NorthJetty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to On This Page.
        /// </summary>
        public static string OnThisPage {
            get {
                return ResourceManager.GetString("OnThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Register an account.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to To book space at the Esquimalt Graving Dock, you must have an account.
        /// </summary>
        public static string RegistrationDisclaimer {
            get {
                return ResourceManager.GetString("RegistrationDisclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Section.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Section menu.
        /// </summary>
        public static string SectionMenu {
            get {
                return ResourceManager.GetString("SectionMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Select a time period:.
        /// </summary>
        public static string SelectTimePeriod {
            get {
                return ResourceManager.GetString("SelectTimePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to yyyy-MM-dd.
        /// </summary>
        public static string ShortDate {
            get {
                return ResourceManager.GetString("ShortDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to If you have an account, sign in to view current listings, book or cancel a space.
        /// </summary>
        public static string SignInBelow {
            get {
                return ResourceManager.GetString("SignInBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign in to book or cancel a space.
        /// </summary>
        public static string SignInHeader {
            get {
                return ResourceManager.GetString("SignInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sign in to book a space.
        /// </summary>
        public static string SignInToBookSpace {
            get {
                return ResourceManager.GetString("SignInToBookSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to South Jetty.
        /// </summary>
        public static string SouthJetty {
            get {
                return ResourceManager.GetString("SouthJetty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to To Date:.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to a user company request.
        /// </summary>
        public static string UserCompanyRequest {
            get {
                return ResourceManager.GetString("UserCompanyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} user company requests.
        /// </summary>
        public static string UserCompanyRequests {
            get {
                return ResourceManager.GetString("UserCompanyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Vessel.
        /// </summary>
        public static string Vessel {
            get {
                return ResourceManager.GetString("Vessel", resourceCulture);
            }
        }
    }
}
